---
- name: Install Python if needed
  raw: apt -y install python3
  become: true

- name: Install Pip if needed
  apt:
    update_cache: true
    name: python3-pip
    state: present
  become: true

- name: Install UFW if needed
  package:
    name: ufw
    state: present
  become: true

- name: Configure UFW
  ufw:
    state: enabled
    policy: deny
    logging: 'on'
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - 9200
    - 9300
    - 5044
    - 5601
  become: true

- name: Install Docker if needed
  package:
    name: docker.io
    state: present
  become: true

- name: Install Docker python API if needed
  pip:
    name: docker
    state: present
  become: true

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Create docker network
  docker_network:
    name: "{{ elk_docker_network }}"
    driver: bridge
  become: true

- name: Change max virtual memory maps for Elastic
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: true
    sysctl_set: true
